setwd("C:\\Users\\User\\OneDrive\\Desktop\\unreal_psychophysics\\rdas")

load("repeat_jnd.rda")
load("run_unreal_psy.rda")
load("load_thresholds.rda")
load("name_conditions_and_domains.rda")
load("psy_paths.rda")
load("repeat_list.rda")
load("threshold_fix.rda")
load("unreal_psy.rda")
load("remove_staircase.rda")
load("concat_csvs.rda")
